// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI0fN1mHkuyoGK1Xn7hQIaKDDsU3G40c4',
    appId: '1:896997168517:web:5212389d45a3e0174ee0ec',
    messagingSenderId: '896997168517',
    projectId: 'sanatan-guide-7973',
    authDomain: 'sanatan-guide-7973.firebaseapp.com',
    storageBucket: 'sanatan-guide-7973.firebasestorage.app',
    measurementId: 'G-Z0E9VQ1VRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZj3LJOvEzI9HVdxGV4QB_sZ0kMiFk264',
    appId: '1:896997168517:android:02beaaec355debb44ee0ec',
    messagingSenderId: '896997168517',
    projectId: 'sanatan-guide-7973',
    storageBucket: 'sanatan-guide-7973.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM6GDqBnB2y9-85S0-qklyOuUPfuAnCRM',
    appId: '1:896997168517:ios:ee677555cd74d8e74ee0ec',
    messagingSenderId: '896997168517',
    projectId: 'sanatan-guide-7973',
    storageBucket: 'sanatan-guide-7973.firebasestorage.app',
    iosBundleId: 'com.Saurabh7973.sanatanGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM6GDqBnB2y9-85S0-qklyOuUPfuAnCRM',
    appId: '1:896997168517:ios:ee677555cd74d8e74ee0ec',
    messagingSenderId: '896997168517',
    projectId: 'sanatan-guide-7973',
    storageBucket: 'sanatan-guide-7973.firebasestorage.app',
    iosBundleId: 'com.Saurabh7973.sanatanGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI0fN1mHkuyoGK1Xn7hQIaKDDsU3G40c4',
    appId: '1:896997168517:web:d327a8686b44fdfb4ee0ec',
    messagingSenderId: '896997168517',
    projectId: 'sanatan-guide-7973',
    authDomain: 'sanatan-guide-7973.firebaseapp.com',
    storageBucket: 'sanatan-guide-7973.firebasestorage.app',
    measurementId: 'G-BW5WETT7HH',
  );
}
